spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dragon
    password: HXC19970129
    url: jdbc:mysql://localhost/bookstore
  #security:
   # user:
    #  password: password
     # name: user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

